- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: pre-run | check requirements
      tags: always
      package:
        name: python-psutil
        state: latest

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost
  tags: pc
  become: true
  vars:
    home: "/home/{{ ansible_env.SUDO_USER }}"
    user: "{{ ansible_env.SUDO_USER }}"
    ipaddr: "{{ ansible_default_ipv4.address }}"
  vars_prompt:
    - name: git_username
      prompt: git config username
      private: false

    - name: git_email
      prompt: git config email
      private: false
  roles:
    - pc
