- name: gnome | power settings | sleep inactive
  tags: gnome,power settings
  become_user: "{{ user }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type",
        value: "'nothing'",
      }
