- name: Copy wallpaper file
  copy:
    src: files/wallpaper.jpg 
    dest: "{{ home }}/Imagens/wallpaper.jpg"
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0644

- name: Set GNOME wallpaper
  become_user: "{{ user }}"
  dconf: 
    key: "{{ item }}"
    value: "'file://{{ home }}/Imagens/wallpaper.jpg'"
  loop:
   - "/org/gnome/desktop/background/picture-uri" 
   - "/org/gnome/desktop/background/picture-uri-dark" 