- name: install powerlevel10k theme
  tags: powerlevel10k, theme, zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
  notify: "{{ item }}"
  loop:
    - set powerlevel10k for zsh theme
    - source custom p10k config
    - set aliases

- name: set powerlevel10k for zsh theme
  tags: powerlevel10k, theme, zsh
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: ZSH_THEME="powerlevel10k/powerlevel10k"

- name: source custom p10k config
  tags: powerlevel10k, theme, zsh
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: source ~/.p10k.zsh

- name: set aliases
  tags: aliases, zsh
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: |
      # aliases
      alias ssh="kitty +kitten ssh" 
      alias tda="todo.sh add"
      alias td="todo.sh"
      alias tdl="todo.sh ls"
      alias vg="vagrant"
      alias vgu="vagrant up"
      alias vgp="vagrant provision"
      alias vgh="vagrant halt"
      alias vgd="vagrant destroy -f"
      alias ap="ansible-playbook"
      alias kl="kubectl"
      alias klcf="kubectl create -f"
      alias klap="kubectl apply -f"
      alias klgp="kubectl get pods"
      alias klsc='f(){ kubectl config set-context $(kubectl config current-context) --namespace="$1";  unset -f f; }; f'
      alias klcn="kubectl create ns"