- name: software | docker | install package
  tags: docker, packages, workstation-packages
  package:
    name: docker
    state: latest
  notify: "{{ item }}"
    loop:
      - ensure group docker exists
      - add user to docker group
