- name: software | prometheus-node-exporter | install package
  tags: prometheus-node-exporter, packages, workstation-packages
  package:
    name: prometheus-node-exporter
    state: latest

- name: start prometheus-node-exporter service
  tags: prometheus-node-exporter, service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes