- name: software | prometheus | install package
  tags: prometheus, packages, workstation-packages
  package:
    name: prometheus
    state: latest
  notify: "{{ item }}"
  loop:
    - remove original prometheus file
    - set new personal prometheus file
