- name: container | glances | setup container
  community.docker.docker_container:
    name: glances
    image: nicolargo/glances:latest-alpine
    network_mode: host
    pid_mode: host
    ports:
      - 61208:61208
      - 61209:61209
    restart_policy: always
    env:
      GLANCES_OPT: "-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock