- name: container | watchtower | setup container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock