- name: Create a symlink for snap
  tags: snap, snap setup, symlink
  ansible.builtin.shell: ln -s /var/lib/snapd/snap /snap

- name: Config default pamac settings
  tags: system, pamac
  lineinfile:
    path: "/etc/pamac.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: "^MaxParallelDownloads",
        line: MaxParallelDownloads = 10,
      }
    - { regexp: "^#EnableAUR", line: EnableAUR }
    - { regexp: "^#CheckAURUpdates", line: CheckAURUpdates }

- name: Create a dir to mount Secundaty HDD
  tags: HDD, dir
  file:
    path: "/mnt/hdd2"
    state: directory
    mode: "0777"

- name: Mount my secundary HDD on boot
  tags: mount, HDD
  lineinfile:
    path: "/etc/fstab"
    line: "UUID=fbad14bc-c916-442c-9c62-17073c551e07 /mnt/hdd2	ext4	defaults 0 0"
