- name: Create a symlink for snap
  tags: snap, snap setup, symlink
  ansible.builtin.shell: ln -s /var/lib/snapd/snap /snap

- name: Config default pamac settings
  tags: system, pamac
  lineinfile:
    path: "/etc/pamac.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: "^MaxParallelDownloads",
        line: MaxParallelDownloads = 10,
      }
    - { regexp: "^#EnableAUR", line: EnableAUR }
    - { regexp: "^#CheckAURUpdates", line: CheckAURUpdates }
