- name: Reject everything and enable UFW
  tags: firewall, UFW, reject
  community.general.ufw:
    state: enabled
    policy: reject

- name: Allow prometheus
  community.general.ufw:
    rule: allow
    port: 9090
    proto: tcp

- name: Allow prometheus node exporter
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp

- name: Allow glances
  community.general.ufw:
    rule: allow
    port: 61208:61209
    proto: tcp

- name: Allow portainer agent
  community.general.ufw:
    rule: allow
    port: 9001
    proto: tcp

- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16